#!/usr/bin/python
# -*- coding: utf-8 -*-
# 爬虫

import urllib2
from BeautifulSoup import BeautifulSoup
import re
# import MySQLdb

if __name__ == '__main__':
    url = 'http://jianli.58.com/resume/91655325401100'
    content = urllib2.urlopen(url).read()
    soup = BeautifulSoup(content)
    basedata = str(soup.findAll('li', attrs = {'class': 'item'}))
    basedata = re.findall(r'(?<=class="item").*?(?=</li>)', basedata)
    ID = str(soup.findAll('script', attrs={'type': 'text/javascript'}))
    ID = re.findall(r'(?<=global.ids = ").*?(?=";)', ID)
    ID = ID[0].decode('utf-8').encode('utf-8')
    name = basedata[0].decode('utf-8').encode('utf-8')
    sex = basedata[1].decode('utf-8').encode('utf-8')
    age = basedata[2].decode('utf-8').encode('utf-8')
    print(name)

